# Generated by Django 5.0.7 on 2024-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='like',
        ),
        migrations.AddField(
            model_name='coments',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coments',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
