# Generated by Django 5.0.7 on 2024-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lessons_like_coments_like_alter_coments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='lessons',
            unique_together={('name',)},
        ),
    ]
